title: Miri Mertner
email: miri.mertner@proton.me
description: >- # this means to ignore newlines until "baseurl:"
  PhD student in linguistics at the University of Tübingen
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anmiri.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  anmiri

# Build settings
theme: minimal
plugins:
  - jekyll-feed

